# Enter the names of all of your classes here.
classes: 
    1: Wood 2
    2: Forensic Science
    3: English 4
    4: Study 
    5: Economics 
    6: AP Environmental Science 
    7: Calculus

# Enter the description of each class here.
description:
    1: Period 1
    2: Period 2
    3: Period 3
    4: Period 4 
    5: Period 5 
    6: Period 6 
    7: Period 7

# Replace with your own calendar ID or leave blank to use your default calendar.
calendar_id:
    hsk2gtc51g6misvg4k811t8glk@group.calendar.google.com
